---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: mysql
    run_list:
      - recipe[test::prepare_mysql]
      - recipe[codestriker::default]
      - recipe[test::setup_nginx_fastcgi]
    attributes:
      codestriker:
        use_existing_user: true
        user: 'www-data'
        group: 'www-data'

  - name: postgresql
    run_list:
      - recipe[test::prepare_postgresql]
      - recipe[codestriker::default]
      - recipe[test::setup_nginx_fastcgi]
    attributes:
      codestriker:
        use_existing_user: true
        user: 'www-data'
        group: 'www-data'
        db:
          dsn: 'DBI:Pg:dbname=codestrikerdb'
