name             'test'
maintainer       'Matvey Aksenov'
maintainer_email 'matvey.aksenov@gmail.com'
license          'Apache 2.0'
description      'test cookbook'
long_description 'test cookbook'
version          '0.1.0'
