CREATE DATABASE codestrikerdb CHARACTER SET utf8;

GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,DROP,REFERENCES
  ON codestrikerdb.* TO codestriker@localhost IDENTIFIED BY '12345678';

FLUSH PRIVILEGES;
